//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majorproject_web_api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeetravelbookingsystemEntities : DbContext
    {
        public EmployeetravelbookingsystemEntities()
            : base("name=EmployeetravelbookingsystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<travelagent> travelagents { get; set; }
        public virtual DbSet<TravelRequest> TravelRequests { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Usertype> Usertypes { get; set; }
    }
}
