//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majorproject_web_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class travelagent
    {
        public decimal Travel_id { get; set; }
        public string Travel_name { get; set; }
    }
}
