//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majorproject_web_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelRequest
    {
        public decimal Request_Id { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public string From_Location { get; set; }
        public string To_Location { get; set; }
        public Nullable<decimal> User_type_Id { get; set; }
        public string Current_Status { get; set; }
    
        public virtual Usertype Usertype { get; set; }
    }
}
