//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majorproject_web_api.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public decimal Login_Id { get; set; }
        [Required(ErrorMessage = "Youre Username required to continue")]
        public string User_id { get; set; }
        [Required(ErrorMessage = "Your Password required to continue")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public decimal User_type_id { get; set; }
        public string Name { get; set; }
        public string Manager_user_id { get; set; }
    
        public virtual Usertype Usertype { get; set; }

        public string loginErrorMessage { get; set; }
    }
}
